apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab Dashboard
    favicon: https://github.com/gethomepage/homepage/raw/main/public/android-chrome-192x192.png
    theme: dark
    color: blue
    headerStyle: clean
    layout:
      Management:
        style: row
        columns: 3
      Media:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 2
      Infrastructure:
        style: row
        columns: 3

  services.yaml: |
    - Management:
        - ArgoCD:
            href: https://argocd.homelab.local
            description: GitOps Continuous Deployment
            icon: argocd.png
            server: my-argocd
            namespace: argocd

        - Rancher:
            href: https://rancher.homelab.local
            description: Kubernetes Management
            icon: rancher.png

        - Grafana:
            href: https://grafana.homelab.local
            description: Monitoring & Observability
            icon: grafana.png

    - Media:
        - Plex:
            href: https://plex.homelab.local
            description: Media Server
            icon: plex.png

        - Radarr:
            href: https://radarr.homelab.local
            description: Movie Management
            icon: radarr.png

        - Sonarr:
            href: https://sonarr.homelab.local
            description: TV Show Management
            icon: sonarr.png

        - Prowlarr:
            href: https://prowlarr.homelab.local
            description: Indexer Management
            icon: prowlarr.png

        - qBittorrent:
            href: https://qbittorrent.homelab.local
            description: Download Client
            icon: qbittorrent.png

        - Overseerr:
            href: https://overseerr.homelab.local
            description: Media Request Management
            icon: overseerr.png

    - Infrastructure:
        - CoreDNS:
            href: https://coredns.homelab.local/metrics
            description: DNS Server & Metrics
            icon: coredns.png

        - Traefik:
            href: https://traefik.homelab.local
            description: Reverse Proxy & Load Balancer
            icon: traefik.png

        - Longhorn:
            href: https://longhorn.homelab.local
            description: Distributed Storage
            icon: longhorn.png

    - Monitoring:
        - Grafana:
            href: https://grafana.homelab.local
            description: Monitoring Dashboards
            icon: grafana.png

        - Prometheus:
            href: https://prometheus.homelab.local
            description: Metrics Collection
            icon: prometheus.png


  widgets.yaml: |
    - logo:
        icon: https://github.com/gethomepage/homepage/raw/main/public/android-chrome-192x192.png

    - greeting:
        text_size: xl
        text: "Welcome to your Homelab! ♡"

    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true

    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank

  kubernetes.yaml: |
    mode: cluster

  docker.yaml: ""

  custom.css: |
    /* Cinnamoroll Dark Theme */
    body {
      background: linear-gradient(135deg, #263238 0%, #332233 50%, #2B2D42 100%) !important;
      background-attachment: fixed !important;
    }
    
    :root {
      --color-primary: #6B73FF;
      --color-secondary: #9C88FF;
      --color-accent: #F0F8FF;
      --color-text: #4682B4;
    }
    
    .bg-theme-50 {
      background-color: rgba(240, 248, 255, 0.05) !important;
    }
    
    .text-theme-600 {
      color: var(--color-text) !important;
    }
    
    .border-theme-200 {
      border-color: rgba(156, 136, 255, 0.3) !important;
    }
    
    .group:hover .group-hover\:bg-theme-100 {
      background-color: rgba(107, 115, 255, 0.1) !important;
    }
    
    .shadow-md {
      box-shadow: 0 4px 6px -1px rgba(107, 115, 255, 0.2) !important;
    }

  bookmarks.yaml: |
    - Homelab Links:
        - Documentation:
            - href: https://github.com/gethomepage/homepage
              description: Homepage Documentation

        - Kubernetes:
            - href: https://kubernetes.io/docs/
              description: Kubernetes Documentation
            - href: https://k3s.io/
              description: K3s Documentation

        - Media Management:
            - href: https://wiki.servarr.com/
              description: Servarr Wiki (Radarr/Sonarr/etc)
            - href: https://support.plex.tv/
              description: Plex Support