apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage-serviceaccount
      initContainers:
      - name: config-setup
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          ls -la /tmp/config/
          cp /tmp/config/* /app/config/ 2>/dev/null || true
          ls -la /app/config/
          chmod -R 755 /app/config
        volumeMounts:
        - name: config-source
          mountPath: /tmp/config
        - name: config-writable
          mountPath: /app/config
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_VAR_TITLE
          value: "Homelab Dashboard"
        - name: HOMEPAGE_VAR_SEARCH_PROVIDER
          value: "duckduckgo"
        - name: HOMEPAGE_VAR_HEADER_STYLE
          value: "clean"
        - name: HOMEPAGE_VAR_WEATHER_API_KEY
          value: ""
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "homepage.homelab.local,homelab.local,dashboard.homelab.local,192.168.87.10"
        - name: HOMEPAGE_VAR_GRAFANA_USERNAME
          valueFrom:
            secretKeyRef:
              name: homepage-credentials
              key: grafana-username
        - name: HOMEPAGE_VAR_GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: homepage-credentials
              key: grafana-password
        volumeMounts:
        - name: config-writable
          mountPath: /app/config
        - name: logs
          mountPath: /app/config/logs
      volumes:
      - name: config-source
        configMap:
          name: homepage-config
      - name: config-writable
        emptyDir: {}
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-serviceaccount
  namespace: homepage
  labels:
    app: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["traefik.containo.us", "traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-role
subjects:
- kind: ServiceAccount
  name: homepage-serviceaccount
  namespace: homepage