---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app: qbittorrent-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-exporter
  template:
    metadata:
      labels:
        app: qbittorrent-exporter
    spec:
      containers:
      - name: qbittorrent-exporter
        image: esanchezm/prometheus-qbittorrent-exporter:latest
        ports:
        - containerPort: 8000
          name: metrics
        env:
        - name: QBITTORRENT_BASE_URL
          value: "http://qbittorrent.media.svc.cluster.local:8080"
        - name: QBITTORRENT_HOST
          value: "qbittorrent.media.svc.cluster.local"
        - name: QBITTORRENT_PORT
          value: "8080"
        - name: QBITTORRENT_USERNAME
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: qbittorrent-username
        - name: QBITTORRENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: media-api-keys
              key: qbittorrent-password
        - name: METRICS_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app: qbittorrent-exporter
spec:
  selector:
    app: qbittorrent-exporter
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app: qbittorrent-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: qbittorrent-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - monitoring