apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app: longhorn
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
  - port: manager
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - longhorn-system