apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authelia
  namespace: monitoring
  labels:
    app: authelia
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: authelia
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - authelia
