apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage-1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3600Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage-2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3600Gi