# NOTE: Create this secret manually with your GitHub PAT
# kubectl create secret generic homelab-repo-secret \
#   --from-literal=type=git \
#   --from-literal=url=https://github.com/stevenechadwick/homelab.git \
#   --from-literal=password=YOUR_GITHUB_PAT \
#   --from-literal=username=stevenechadwick \
#   -n argocd
# kubectl label secret homelab-repo-secret argocd.argoproj.io/secret-type=repository -n argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true