apiVersion: v1
kind: Secret
metadata:
  name: homelab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/stevenechadwick/homelab.git
  password: GITHUB_TOKEN
  username: stevenechadwick
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevenechadwick/homelab.git
    targetRevision: HEAD
    path: gitops-repo/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true