apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: homelab-local-db
          configMap:
            name: homelab-local-db
      containers:
        - name: coredns
          volumeMounts:
            - name: homelab-local-db
              mountPath: /etc/coredns/homelab.local.db
              subPath: homelab.local.db