apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: default
  source:
    repoURL: https://github.com/jetstack/cert-manager.git
    targetRevision: release-1.14.4
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: installCRDs
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}