all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_pass: localhost
    ansible_become: yes
    ansible_become_pass: localhost
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            node01:
              ansible_host: 192.168.87.101
              k3s_role: master
        workers:
          hosts:
            node02:
              ansible_host: 192.168.87.102
              k3s_role: worker
            node03:
              ansible_host: 192.168.87.103
              k3s_role: worker
              media_storage: true
              hdd_devices:
                - /dev/sda
                - /dev/sdb
            node04:
              ansible_host: 192.168.87.104
              k3s_role: worker