apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
spec:
  project: default
  source:
    repoURL: 'https://github.com/stevenechadwick/homelab'
    path: config/coredns
    targetRevision: HEAD
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated: {}