---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgC2ovRjFmL9+s1WAkIR4vvW0MUDaXIp6AFYH4Y/gk2cSy+0UoHtgiiYDIh9Fw7lPPK22XqPNONFc3swZVgOUumlG5xwSTKuywKlyulf6/JuhPUfDNgZcPuKQVBm85LKLxUnKEYh/nFezN82DuecgqbZX0ET+BbrfJjvUWyJ3X5b2u0KMb6jEJd67BrhLIQhAYhof4yGTPKJfyk3GY6kSptkYGoEK6CxElukLSxB8XtlYwiQBnzbGPjO2BGM4/HdKiJU/Iu+k9uwDuUEuAdLqkZMS1fNZS5BzKmM0cpgRdQJY+t2s0nLEy2XeN20NVrTmMMwLK/OFDAt3XWgHCxU9Kg9xvvDz+qvVK2fOZdFioyKrj2sLQw5UJUViwtadetGbmbM7sD0BTW3YIXizRVtkp7cFNM7OCAKC3Cm4SEWBusyGZSHoMtkV+FCBWzF3Hw2KNauAkmnmIWQGS+9Ze8hgrU7eq8a1TpdcF9cU8NMuyTSTF9JvlknRZjeHkM6CxQiarMV48JBVWrtEuR+wDNK3GgCRk8VBUUZbKfaRGmhWK9PvVfCGyqEZRvWjL0zZHRN8pP6PdFBongfDqnxArXrhGQ+jLpkvrvHlFcv5ZY8PN9uztT6G2OQevBkLxhPoBdqgVYgwsJFSgzPUnVdDeFLSINco5ZB1BqzBkOg/DTTbRQKiYLLoFnN3g/UaxTENlKuUr0BXtechWxcDQzGWsp5fFB4Olb0IyOiXCh4JQE7U4lkkGl7Bg4CDZaAPp30dfuuXa6l2zuPCOwyvNGzJctIv+JoGKEJq+N5/HJ94hC0aiqpQCFI4WXnLWPkIl0eUJmz234G+NU1WiNyc6uCOaUD4XJozy4CSQ3yXBFhw03R+E0fVUdfxRBLhdFLrtn2J7PpcN3NJ/cKJBk9BvwcLhUcTwm+K5PzTATWVSl8+Wn3UCdhEf65BChW1w2qwH5BBglxRpGTqTxNN179ZW43hUggtkZiOlDazy+xYkcXdd+bXyQ+B1XzXVh39CZ05N3raqamN+WM/vX+6GiisV23KRM3lvvKhZuT0GhwgA+OSzP70DCxk98nxOcvBXVJJ9ubjTVGVxU/bzhDx28qA/rsa+M70UATN1rU8ggyFz/RoLsSzFV478B5dkPQo22xwlCa55jJPZWbnnLVakje4lZLqpHCnI5O7s/5x3cXG0GHnmqdtSIAWR4NfuZajBVnRBv55bm4vGpFaosbPbsQ+blDbbu2Z5sE6B9DCZjg+ZNm0Fy8RM5O2BGIdHarPiAKGkfDfkg=
  template:
    metadata:
      creationTimestamp: null
      name: authelia-users
      namespace: authelia
    type: Opaque
