apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: http
    port: 80
    targetPort: 9091
  - name: metrics
    port: 9959
    targetPort: 9959
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: authelia-simple
  namespace: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: http
    port: 80
    targetPort: 9091
  type: ClusterIP