---
- name: Test connectivity to all nodes
  hosts: k3s_cluster
  gather_facts: yes
  tasks:
    - name: Ping all nodes
      ping:
      
    - name: Get hostname and uptime
      command: "{{ item }}"
      register: system_info
      loop:
        - hostname
        - uptime
        
    - name: Display system information
      debug:
        msg: "{{ inventory_hostname }}: {{ item.stdout }}"
      loop: "{{ system_info.results }}"
      
    - name: Check disk space
      command: df -h
      register: disk_space
      
    - name: Display disk space
      debug:
        var: disk_space.stdout_lines