---
- name: Copy kubeconfig from control plane
  hosts: master
  tasks:
    - name: Copy k3s kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/../../kubeconfig-homelab"
        flat: yes
        
    - name: Display kubeconfig content
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content
      
    - name: Show kubeconfig
      debug:
        msg: "{{ kubeconfig_content.content | b64decode }}"