apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-runner

resources:
  - namespace.yaml
  - pvc.yaml
  - sealed-runner-pat.yaml
  - sealed-gitea-registry.yaml
  - runner-deployment.yaml
