apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-homelab-tls
  namespace: media
spec:
  secretName: overseerr-homelab-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - overseerr.homelab.local