grafana:
  adminPassword: admin
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.87.13
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    retention: 30d

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi