apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    [server]
    DOMAIN = gitea.homelab.local
    ROOT_URL = https://gitea.homelab.local/
    SSH_DOMAIN = gitea.homelab.local

    [packages]
    ENABLED = true

    [actions]
    ENABLED = true
    DEFAULT_ACTIONS_URL = https://github.com
