apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-config
  namespace: gitea
data:
  config.yaml: |
    log:
      level: debug

    runner:
      file: .runner
      capacity: 1
      timeout: 3h
      insecure: true
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - "ubuntu-latest:docker://catthehacker/ubuntu:act-22.04"
        - "ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04"

    cache:
      enabled: true
      dir: /root/.cache/actcache

    container:
      options: >-
        -e DOCKER_HOST=tcp://host.docker.internal:2375
        --add-host=host.docker.internal:host-gateway
        --add-host=gitea.homelab.local:10.43.46.7
      workdir_parent: workspace
