---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-credentials
  namespace: gitea
spec:
  encryptedData:
    GITEA_ADMIN_PASSWORD: AgCeSb7S9bVH3Fz6oGg2rxKGYU1ouQei8PnPE4H9jHBMnrJe2Hy/GGduymQ6QKT7wGYsHoOCFh9j1Mnz/m+MznmFa12tEGS1ZmOf++5Wkwyyux3JtrwiQOf/DhShe9mAFT/EDF0e9JzLqhnSiZaB3ZiVffXU/GUfkRg8mhALs0L39cbIn1FsE3TTrLhN6V7QMaD/1v1MuCwQkW+x5XiYuJQpS+tB1vfptC+kUxIZl5/UPnEdL1owuPiDTBw+g1AOkew2FuLoBvk7dBe6pygTBua0Vzkrh+UN5v7xG1uYur2F1xUaMoZfi+HHTrOwUt1ei3K8GJw79nu3IPnUdrmPlB9EChp0Iuen3KMT46UdXv++EyK9QavyOAKeql+juraw2SxyU+TScgqZbLNQTBJYJPYKIGexCqFZGVPa83MM4ZnUbuVWhdRo1IyzSTumbGZZxHsbnpjS5moLqFecV5CHd5DxW0341+dAidUoE8LbIns9irI9pkiJw7dUANNi4H6e8FYjFJ12BeJZd6RH5ov5hBEZarvHp4ST7eDcA4q3vp21Poc0zv81YUIlhxw+mxqYaTtKXLauTTDNqT/dfnGzGwRTyXkvY5cpO4kFCLjB1SyPleIA9dCLAVsuPtc1WPbXOvO6xtdszMkNo/e81UZMnrIgptMVlR5jq2l5Imyj0wg6gs8S7IAeokXNXYQGI0qkI3ai/OhIZsZkBdTwnbW8v8e8FAZ0eD8pwwA=
    GITEA_ADMIN_USERNAME: AgBzmGIMyUIvkXPp2UmwN3kaYHjsVbncH7bN8lzy4DzPv6KWJ0tKYEBWfjV19hPo+KmGc4afQuQA/FzYl84dQE6gOtFqNKokckDvvNeZMudl5Ej4ByCDIMCIOKnL6SR/PLhOCpZTcopqNzV3gQCvueAO0U70tZN3RP7wfhMax6GsO204Ll8DKpK7v738bLbs07FUi7qDb7BXapU59bOi2WJ+P/sPsyoJkuOpdXw/jNp7jXzbgK5iEfsOPiwrsepVzHaAL5A1pZ5VLJxNgkUH18CorPLePbYAzXh0JHRgd9kcoQoQ1e5x8FlayDQvm9McXfMwacojAXul3o13A0OR6QXkxjKSVR68+elo70vX2Mzk4t0IihIPvePeTKXTYSnVQnbXcAoC8YHOlpLuwIQ+9QxNE8AruKwAcmF34S60g1xCIsqoHiXWir7IFYD0a32os5HkGAL/KrKTBQ0JY4ex6rjuhqkEyj4yv7fRm/LhIob5Igv8YZ2nI9u26/Q8zoslab9Nt6B5N7tJ7yaf4X7z0mCrNkZdfUxA09X109jiwDXWe5vchxYcQd2vDrClJaCXZmDvMC1pvwcFzjPDKM13UZB0KVFpxOUjgcFeiiKSkesth3RQqr1EWhnDeKc2uz9zPUek3SeXiVb9tR0iDuknHebO6k8xRALJeAI8TzF7w3jsIUoA1pXWWUcdU2TWd4VPNJ9RZH6GTAiOzOP3cA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitea
      name: gitea-admin-credentials
      namespace: gitea
    type: Opaque
